export const frcConfig = {
  title: "Maximum Indebtedness by FRC",
  subTitle: "Risk Score",
  totalScoreLabel: "Total Score",
  totalScoreMax: "/200",
  seniorityLabel: "Seniority of 10 years",
  seniorityMax: "/200",
  centralRiskLabel: "Central Risk of 250 P",
  centralRiskMax: "/200",
  employmentStabilityLabel: "Employment Stability Index 900 P",
  employmentStabilityMax: "/300",
  maritalStatusLabel: "Marital Status",
  maritalStatusMax: "/50",
  economicActivityLabel: "Economic Activity",
  economicActivityMax: "/200",
  incomesLabel: "Monthly Income",
  maxIndebtedness: "Maximum Indebtedness",
  timesIncome: "No. of times income for this scoring",
  closeBtn: "Close"
};
