export const frcConfig = {
  title: "Endeudamiento máximo x FRC",
  subTitle: "Score de riesgo",
  totalScoreLabel: "Puntaje total",
  totalScoreMax: "/200",
  seniorityLabel: "Antigüedad de 10 años",
  seniorityMax: "/200",
  centralRiskLabel: "Central de riesgo de 250 P",
  centralRiskMax: "/200",
  employmentStabilityLabel: "Índice de estabilidad laboral 900 P",
  employmentStabilityMax: "/300",
  maritalStatusLabel: "Estado civil - Casado",
  maritalStatusMax: "/50",
  economicActivityLabel: "Actividad economica - Pensionado",
  economicActivityMax: "/200",
  incomesLabel: "Ingresos mensuales",
  timesIncome: "No. de veces el ingreso para este scoring",
  maxIndebtedness: "Endeudamiento máximo",
  closeBtn: "Cerrar"
};
